apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      serviceAccountName: backend-sa

      containers:
        - name: backend
          image: BACKEND_IMAGE

          ports:
            - containerPort: 3000

          env:
            - name: DB_SECRET_NAME
              value: "DB_SECRET_NAME"

            - name: AWS_REGION
              value: "AWS_REGION"

            - name: APP_VERSION
              value: "VERSION_TAG"

          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5